# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: b477d40
_src_path: https://github.com/MartinBernstorff/nimble-python-template
email: martinbernstorff@gmail.com
full_name: Martin Bernstorff
github_username: MartinBernstorff
package_name: memorymarker
project_name: memorymarker
project_slug: memorymarker
python_version: '3.12'
release_docker_image: true
release_package: true
