name: docker-smoketest
on:
  pull_request:

jobs:
  smoketests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Get environment variables
        run: |
          echo "OMNIVORE_API_KEY=${{ secrets.OMNIVORE_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env

      - name: Run integration test
        shell: bash
        run: |
          make docker-smoketest
