name: test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build CI container
        run: |
          make docker_ci