name: test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build CI container
        env:
          OMNIVORE_API_KEY: ${{ secrets.OMNIVORE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo $OMNIVORE_API_KEY >> .env
          echo $secrets.OPENAI_API_KEY >> .env
          make docker_ci