name: test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "ghcr.io/martinbernstorff/memorymarker_ci:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build CI container
        env:
          OMNIVORE_API_KEY: ${{ secrets.OMNIVORE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo $OMNIVORE_API_KEY >> .env
          echo $OPENAI_API_KEY >> .env
          make docker_ci